name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: '3.11' }

    - name: Install host build packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config unzip openjdk-17-jdk

    - name: Install buildozer & deps
      run: |
        python -m pip install -U pip
        pip install buildozer==1.5.0 "kivy[base]==2.3.1" pymunk pillow cython==0.29.36

    - name: Build debug APK
      run: buildozer -v android debug

    - uses: actions/upload-artifact@v4
      with:
        name: flappy-debug-apk
        path: bin/*-debug*.apk
