name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5    # Python 3.11
      with: { python-version: '3.11' }

    - name: Install buildozer & deps
      run: |
        python -m pip install -U pip
        # ① buildozer 1.5.0 是最新发布版
        pip install buildozer==1.5.0 "kivy[base]==2.3.1" pymunk pillow
        # ② Cython 0.29.* 与 p4a 最兼容
        pip install cython==0.29.36

    - name: Build debug APK
      run: buildozer -v android debug

    - uses: actions/upload-artifact@v4
      with:
        name: flappy-debug-apk
        path: bin/*-debug*.apk
