name: Build APK (Docker)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Fix workspace perms for container
      run: sudo chown -R 1000:1000 "$GITHUB_WORKSPACE"

    - name: Build debug APK inside Docker
      run: |
        docker run --rm \
          -v "${{ github.workspace }}":/app -w /app \
          ghcr.io/kivy/buildozer:latest \
          android debug                

    - uses: actions/upload-artifact@v4
      with:
        name: flappy-debug-apk
        path: bin/*-debug*.apk
